// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG11jyc_ureYDLPD1A_Pt8dnxJ_rnCjVM',
    appId: '1:857060472703:web:160667af5021c4316d4c4a',
    messagingSenderId: '857060472703',
    projectId: 'update-device-notification',
    authDomain: 'update-device-notification.firebaseapp.com',
    storageBucket: 'update-device-notification.appspot.com',
    measurementId: 'G-NC94XTHC0V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsptmHgB4s3NZL6NDUGvPm7GG5WoEie5k',
    appId: '1:857060472703:android:0b8d20f6890384926d4c4a',
    messagingSenderId: '857060472703',
    projectId: 'update-device-notification',
    storageBucket: 'update-device-notification.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBWm5txxJ5tHdDODZi2BR44cwYFKtlzsk',
    appId: '1:857060472703:ios:5fd9fda3198fdfaa6d4c4a',
    messagingSenderId: '857060472703',
    projectId: 'update-device-notification',
    storageBucket: 'update-device-notification.appspot.com',
    iosBundleId: 'com.example.updateDeviceNitifications',
  );
}
